name: pugo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - biopython==1.81
  - fair-esm==2.0.0
  - click
  - pandas
  - pip
  - pip:
    - wandb
    - scikit-learn
    - tqdm
    - requests
