name: deepgopu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - biopython==1.81
  - fair-esm==2.0.0
  - click
  - JPype1=1.4.1
  - pandas
  - pytorch
  - pytorch-cuda==11.8
  - pip
  - pip:
      - mowl-borg>=0.2.0
